{{- if .Values.adminUi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin-ui
  labels:
    {{- include "auth-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin-ui
spec:
  type: {{ .Values.adminUi.service.type }}
  ports:
    - name: http
      port: {{ .Values.adminUi.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: admin-ui
{{- end }}
